// ─── lib/exercises/exerciseLibrary.ts ────────────────────────────────────────
// Kinesiology-grade exercise database.
// Pure data — no React, no imports, no side effects.
// Categories: Upper Push | Upper Pull | Lower Quad | Lower Posterior | Core | Full Body | Mobility

export type MovementPattern =
  | "Horizontal Push"
  | "Vertical Push"
  | "Horizontal Pull"
  | "Vertical Pull"
  | "Squat"
  | "Hinge"
  | "Carry"
  | "Rotation"
  | "Anti-Rotation"
  | "Isometric"
  | "Explosive"
  | "Mobility"
  | "Stability";

export type DifficultyLevel = "Beginner" | "Intermediate" | "Advanced";

export type MuscleCategory =
  | "Upper Push"
  | "Upper Pull"
  | "Lower Quad"
  | "Lower Posterior"
  | "Core"
  | "Full Body"
  | "Mobility";

export type EquipmentCategory =
  | "barbell"
  | "dumbbell"
  | "cable"
  | "machine"
  | "bodyweight"
  | "kettlebell"
  | "resistance_band"
  | "pullup_bar"
  | "other";

export type TrainingEnvironment =
  | "gym"
  | "home_gym"
  | "dumbbells_only"
  | "bodyweight_only";

export interface Exercise {
  name: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  movementPattern: MovementPattern;
  difficulty: DifficultyLevel;
  equipment: string;
  biomechanicalNote: string;
  category: MuscleCategory;
  equipmentCategory?: EquipmentCategory;
  trainingEnvironment?: TrainingEnvironment[];
}

// ─── UPPER PUSH — Chest / Shoulders / Triceps (28 exercises) ─────────────────

export const upperPushExercises: Exercise[] = [

  // ── Beginner ────────────────────────────────────────────────────────────────

  {
    name: "Machine Chest Press",
    primaryMuscles: ["Pectoralis Major"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps"],
    movementPattern: "Horizontal Push",
    difficulty: "Beginner",
    equipment: "Machine",
    biomechanicalNote: "Fixed movement arc reduces scapular control demand, making it safe for learning horizontal pressing mechanics.",
    category: "Upper Push",
  },
  {
    name: "Pec Deck (Chest Fly Machine)",
    primaryMuscles: ["Pectoralis Major"],
    secondaryMuscles: ["Anterior Deltoid"],
    movementPattern: "Horizontal Push",
    difficulty: "Beginner",
    equipment: "Machine",
    biomechanicalNote: "Isolates pectoral adduction through a fixed arc with no rotator cuff stabilisation demand.",
    category: "Upper Push",
  },
  {
    name: "Machine Shoulder Press",
    primaryMuscles: ["Anterior Deltoid", "Medial Deltoid"],
    secondaryMuscles: ["Triceps", "Upper Trapezius"],
    movementPattern: "Vertical Push",
    difficulty: "Beginner",
    equipment: "Machine",
    biomechanicalNote: "Guided vertical pressing path reduces scapular upward rotation demand relative to barbell overhead press.",
    category: "Upper Push",
  },
  {
    name: "Push-Up (Standard)",
    primaryMuscles: ["Pectoralis Major"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps", "Serratus Anterior"],
    movementPattern: "Horizontal Push",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Closed-chain horizontal press requiring serratus anterior activation for dynamic scapular protraction throughout the movement.",
    category: "Upper Push",
  },
  {
    name: "Incline Push-Up",
    primaryMuscles: ["Pectoralis Major (lower fibres)"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps"],
    movementPattern: "Horizontal Push",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Reduced bodyweight load fraction (approx. 60%) makes this the primary regression for standard push-up.",
    category: "Upper Push",
  },
  {
    name: "Seated Dumbbell Shoulder Press",
    primaryMuscles: ["Anterior Deltoid", "Medial Deltoid"],
    secondaryMuscles: ["Triceps", "Upper Trapezius", "Serratus Anterior"],
    movementPattern: "Vertical Push",
    difficulty: "Beginner",
    equipment: "Dumbbells",
    biomechanicalNote: "Seated position eliminates lower-body drive, isolating shoulder pressing strength with independent arm paths.",
    category: "Upper Push",
  },
  {
    name: "Dumbbell Chest Press (Flat, Light)",
    primaryMuscles: ["Pectoralis Major"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps"],
    movementPattern: "Horizontal Push",
    difficulty: "Beginner",
    equipment: "Dumbbells, Bench",
    biomechanicalNote: "Independent arm paths require more rotator cuff co-contraction than barbell but allow natural wrist pronation.",
    category: "Upper Push",
  },
  {
    name: "Cable Tricep Pushdown (Rope)",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: ["Anconeus"],
    movementPattern: "Vertical Push",
    difficulty: "Beginner",
    equipment: "Cable Machine",
    biomechanicalNote: "Constant cable tension maintains load through full elbow extension range; rope attachment allows forearm supination at terminal extension.",
    category: "Upper Push",
  },
  {
    name: "Overhead Tricep Extension (Dumbbell, Two-Hand)",
    primaryMuscles: ["Triceps Brachii (long head)"],
    secondaryMuscles: ["Anconeus"],
    movementPattern: "Vertical Push",
    difficulty: "Beginner",
    equipment: "Dumbbell",
    biomechanicalNote: "Shoulder-flexed position places long head of triceps under stretch, increasing active tension and hypertrophy stimulus.",
    category: "Upper Push",
  },

  // ── Intermediate ─────────────────────────────────────────────────────────────

  {
    name: "Barbell Bench Press (Flat)",
    primaryMuscles: ["Pectoralis Major"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps"],
    movementPattern: "Horizontal Push",
    difficulty: "Intermediate",
    equipment: "Barbell, Bench",
    biomechanicalNote: "Bilateral loaded horizontal press; scapular retraction and depression on bench reduces impingement risk at glenohumeral joint.",
    category: "Upper Push",
  },
  {
    name: "Barbell Overhead Press (Standing)",
    primaryMuscles: ["Anterior Deltoid", "Medial Deltoid"],
    secondaryMuscles: ["Triceps", "Upper Trapezius", "Serratus Anterior", "Core"],
    movementPattern: "Vertical Push",
    difficulty: "Intermediate",
    equipment: "Barbell",
    biomechanicalNote: "Standing position requires lumbopelvic neutral and full scapular upward rotation; highest axial stability demand of all pressing variations.",
    category: "Upper Push",
  },
  {
    name: "Dumbbell Incline Press",
    primaryMuscles: ["Pectoralis Major (clavicular head)"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps"],
    movementPattern: "Horizontal Push",
    difficulty: "Intermediate",
    equipment: "Dumbbells, Incline Bench",
    biomechanicalNote: "30–45° incline shifts force vector to increase clavicular head activation; independent arm paths allow greater pectoral stretch at bottom.",
    category: "Upper Push",
  },
  {
    name: "Dumbbell Arnold Press",
    primaryMuscles: ["Anterior Deltoid", "Medial Deltoid"],
    secondaryMuscles: ["Posterior Deltoid", "Triceps", "Upper Trapezius"],
    movementPattern: "Vertical Push",
    difficulty: "Intermediate",
    equipment: "Dumbbells",
    biomechanicalNote: "Pronation-to-supination rotation through the press arc recruits all three deltoid heads across different joint angles.",
    category: "Upper Push",
  },
  {
    name: "Cable Chest Fly (Low-to-High)",
    primaryMuscles: ["Pectoralis Major (clavicular head)"],
    secondaryMuscles: ["Anterior Deltoid"],
    movementPattern: "Horizontal Push",
    difficulty: "Intermediate",
    equipment: "Cable Machine",
    biomechanicalNote: "Upward force vector from low cable pulley preferentially loads sternal and clavicular fibres through full adduction range.",
    category: "Upper Push",
  },
  {
    name: "Dips (Chest-Forward Lean)",
    primaryMuscles: ["Pectoralis Major (lower/sternal)"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps"],
    movementPattern: "Vertical Push",
    difficulty: "Intermediate",
    equipment: "Parallel Bars",
    biomechanicalNote: "Forward trunk lean shifts load from triceps-dominant to pectoral-dominant; requires 90°+ shoulder extension mobility.",
    category: "Upper Push",
  },
  {
    name: "Close-Grip Barbell Bench Press",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: ["Pectoralis Major", "Anterior Deltoid"],
    movementPattern: "Horizontal Push",
    difficulty: "Intermediate",
    equipment: "Barbell, Bench",
    biomechanicalNote: "Narrowed grip reduces pectoral moment arm and increases elbow extension demand; wrists must remain stacked over elbows.",
    category: "Upper Push",
  },
  {
    name: "EZ-Bar Skull Crusher",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: ["Anconeus"],
    movementPattern: "Horizontal Push",
    difficulty: "Intermediate",
    equipment: "EZ-Bar, Bench",
    biomechanicalNote: "Elbow fixed in 90° shoulder flexion isolates triceps through full elbow extension range; EZ-bar reduces wrist pronation stress vs. straight bar.",
    category: "Upper Push",
  },
  {
    name: "Dumbbell Lateral Raise (Standing)",
    primaryMuscles: ["Medial Deltoid"],
    secondaryMuscles: ["Anterior Deltoid", "Supraspinatus", "Upper Trapezius"],
    movementPattern: "Vertical Push",
    difficulty: "Intermediate",
    equipment: "Dumbbells",
    biomechanicalNote: "Slight forward lean and internal rotation of thumb-down positions medial deltoid at optimal length-tension; stop at 90° to avoid impingement.",
    category: "Upper Push",
  },
  {
    name: "Cable Lateral Raise (Single-Arm)",
    primaryMuscles: ["Medial Deltoid"],
    secondaryMuscles: ["Supraspinatus", "Upper Trapezius"],
    movementPattern: "Vertical Push",
    difficulty: "Intermediate",
    equipment: "Cable Machine",
    biomechanicalNote: "Constant lateral cable tension maintains load at bottom of range — a mechanical advantage over dumbbells which have zero tension at rest.",
    category: "Upper Push",
  },

  // ── Advanced ─────────────────────────────────────────────────────────────────

  {
    name: "Barbell Incline Bench Press",
    primaryMuscles: ["Pectoralis Major (clavicular head)"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps"],
    movementPattern: "Horizontal Push",
    difficulty: "Advanced",
    equipment: "Barbell, Incline Bench",
    biomechanicalNote: "High load capacity incline variation; requires significant anterior shoulder mobility and scapular upward rotation to avoid impingement under load.",
    category: "Upper Push",
  },
  {
    name: "Weighted Dips",
    primaryMuscles: ["Pectoralis Major", "Triceps Brachii"],
    secondaryMuscles: ["Anterior Deltoid", "Core"],
    movementPattern: "Vertical Push",
    difficulty: "Advanced",
    equipment: "Parallel Bars, Weight Belt",
    biomechanicalNote: "External loading increases glenohumeral stress; requires robust shoulder and pectoral strength base before loading.",
    category: "Upper Push",
  },
  {
    name: "Landmine Press (Single-Arm)",
    primaryMuscles: ["Anterior Deltoid", "Pectoralis Major (clavicular)"],
    secondaryMuscles: ["Triceps", "Core", "Serratus Anterior"],
    movementPattern: "Vertical Push",
    difficulty: "Advanced",
    equipment: "Barbell, Landmine Attachment",
    biomechanicalNote: "Arc press path from hip to overhead reduces impingement risk vs. vertical press while loading single-arm stability through a longer moment arm.",
    category: "Upper Push",
  },
  {
    name: "Single-Arm Dumbbell Bench Press",
    primaryMuscles: ["Pectoralis Major"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps", "Core (anti-rotation)"],
    movementPattern: "Horizontal Push",
    difficulty: "Advanced",
    equipment: "Dumbbell, Bench",
    biomechanicalNote: "Unilateral load creates rotational torque requiring oblique and contralateral lat co-contraction for spinal stabilisation.",
    category: "Upper Push",
  },
  {
    name: "Barbell Floor Press",
    primaryMuscles: ["Pectoralis Major", "Triceps Brachii"],
    secondaryMuscles: ["Anterior Deltoid"],
    movementPattern: "Horizontal Push",
    difficulty: "Advanced",
    equipment: "Barbell",
    biomechanicalNote: "Floor contact eliminates the stretch reflex at bottom position, increasing pure pressing strength demand; also limits shoulder extension reducing impingement risk.",
    category: "Upper Push",
  },
  {
    name: "Decline Barbell Bench Press",
    primaryMuscles: ["Pectoralis Major (sternal/lower)"],
    secondaryMuscles: ["Triceps", "Anterior Deltoid"],
    movementPattern: "Horizontal Push",
    difficulty: "Advanced",
    equipment: "Barbell, Decline Bench",
    biomechanicalNote: "Decline angle shifts load to lower sternal fibres with reduced anterior shoulder stress; elevated blood pressure risk from inverted position requires healthy cardiovascular baseline.",
    category: "Upper Push",
  },
  {
    name: "Cable Single-Arm Chest Fly (High-to-Low)",
    primaryMuscles: ["Pectoralis Major (sternal)"],
    secondaryMuscles: ["Anterior Deltoid"],
    movementPattern: "Horizontal Push",
    difficulty: "Advanced",
    equipment: "Cable Machine",
    biomechanicalNote: "Peak tension at mid-range of adduction matches pectoralis major length-tension curve better than dumbbell fly.",
    category: "Upper Push",
  },
  {
    name: "Push-Up with Feet Elevated (Decline Push-Up)",
    primaryMuscles: ["Pectoralis Major (clavicular)", "Anterior Deltoid"],
    secondaryMuscles: ["Triceps", "Serratus Anterior"],
    movementPattern: "Horizontal Push",
    difficulty: "Advanced",
    equipment: "Bodyweight, Bench",
    biomechanicalNote: "Foot elevation increases upper body load fraction and shifts force vector to upper pectoral and anterior deltoid fibres.",
    category: "Upper Push",
  },
  {
    name: "JM Press",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: ["Pectoralis Major"],
    movementPattern: "Horizontal Push",
    difficulty: "Advanced",
    equipment: "Barbell, Bench",
    biomechanicalNote: "Hybrid between close-grip bench and skull crusher; bar path descends toward throat requiring precise elbow tracking and trained shoulder control.",
    category: "Upper Push",
  },
];

// ─── UPPER PULL — Back / Biceps (26 exercises) ───────────────────────────────

export const upperPullExercises: Exercise[] = [

  // ── Beginner ────────────────────────────────────────────────────────────────

  {
    name: "Lat Pulldown (Wide Grip)",
    primaryMuscles: ["Latissimus Dorsi"],
    secondaryMuscles: ["Biceps Brachii", "Rear Deltoid", "Teres Major", "Rhomboids"],
    movementPattern: "Vertical Pull",
    difficulty: "Beginner",
    equipment: "Cable Machine",
    biomechanicalNote: "Seated, fixed position removes scapular stabilisation complexity; wide grip increases lat stretch at top but reduces bicep contribution.",
    category: "Upper Pull",
  },
  {
    name: "Seated Cable Row (Neutral Grip)",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboids", "Middle Trapezius"],
    secondaryMuscles: ["Biceps Brachii", "Posterior Deltoid", "Erector Spinae"],
    movementPattern: "Horizontal Pull",
    difficulty: "Beginner",
    equipment: "Cable Machine",
    biomechanicalNote: "Neutral grip minimises wrist and elbow stress; seated position stabilises the pelvis allowing focus on scapular retraction mechanics.",
    category: "Upper Pull",
  },
  {
    name: "Machine Chest-Supported Row",
    primaryMuscles: ["Rhomboids", "Middle Trapezius", "Latissimus Dorsi"],
    secondaryMuscles: ["Biceps Brachii", "Posterior Deltoid"],
    movementPattern: "Horizontal Pull",
    difficulty: "Beginner",
    equipment: "Machine",
    biomechanicalNote: "Chest support eliminates lumbar load and compensatory swinging, isolating horizontal pulling musculature.",
    category: "Upper Pull",
  },
  {
    name: "Assisted Pull-Up (Machine)",
    primaryMuscles: ["Latissimus Dorsi"],
    secondaryMuscles: ["Biceps Brachii", "Teres Major", "Rear Deltoid"],
    movementPattern: "Vertical Pull",
    difficulty: "Beginner",
    equipment: "Assisted Pull-Up Machine",
    biomechanicalNote: "Counter-weight reduces effective bodyweight load; allows full range of motion pattern practice before bodyweight capacity is reached.",
    category: "Upper Pull",
  },
  {
    name: "Dumbbell Single-Arm Row (Bench-Supported)",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboids"],
    secondaryMuscles: ["Biceps Brachii", "Posterior Deltoid", "Teres Major"],
    movementPattern: "Horizontal Pull",
    difficulty: "Beginner",
    equipment: "Dumbbell, Bench",
    biomechanicalNote: "Bench support reduces spinal loading, allowing isolated focus on scapular retraction and elbow drive without lower back fatigue.",
    category: "Upper Pull",
  },
  {
    name: "Cable Face Pull (Rope)",
    primaryMuscles: ["Posterior Deltoid", "Infraspinatus", "Teres Minor"],
    secondaryMuscles: ["Middle Trapezius", "Rhomboids", "Biceps Brachii"],
    movementPattern: "Horizontal Pull",
    difficulty: "Beginner",
    equipment: "Cable Machine",
    biomechanicalNote: "External rotation at end range targets rotator cuff external rotators critical for shoulder health; often underloaded relative to internal rotators.",
    category: "Upper Pull",
  },
  {
    name: "Dumbbell Bicep Curl (Seated)",
    primaryMuscles: ["Biceps Brachii"],
    secondaryMuscles: ["Brachialis", "Brachioradialis"],
    movementPattern: "Vertical Pull",
    difficulty: "Beginner",
    equipment: "Dumbbells",
    biomechanicalNote: "Seated position prevents hip flexion momentum, limiting supination at initiation and isolating elbow flexor strength.",
    category: "Upper Pull",
  },
  {
    name: "Cable Curl (Straight Bar)",
    primaryMuscles: ["Biceps Brachii"],
    secondaryMuscles: ["Brachialis", "Brachioradialis"],
    movementPattern: "Vertical Pull",
    difficulty: "Beginner",
    equipment: "Cable Machine",
    biomechanicalNote: "Constant cable tension throughout range eliminates the zero-tension position at bottom found in dumbbell curls.",
    category: "Upper Pull",
  },

  // ── Intermediate ─────────────────────────────────────────────────────────────

  {
    name: "Pull-Up (Bodyweight)",
    primaryMuscles: ["Latissimus Dorsi"],
    secondaryMuscles: ["Biceps Brachii", "Teres Major", "Rear Deltoid", "Core"],
    movementPattern: "Vertical Pull",
    difficulty: "Intermediate",
    equipment: "Pull-Up Bar",
    biomechanicalNote: "Pronated grip increases lat recruitment; requires scapular depression and retraction at initiation before elbow flexion to reduce impingement risk.",
    category: "Upper Pull",
  },
  {
    name: "Chin-Up (Bodyweight)",
    primaryMuscles: ["Latissimus Dorsi", "Biceps Brachii"],
    secondaryMuscles: ["Teres Major", "Pectoralis Major (lower)"],
    movementPattern: "Vertical Pull",
    difficulty: "Intermediate",
    equipment: "Pull-Up Bar",
    biomechanicalNote: "Supinated grip increases biceps brachii contribution via optimal length-tension; slightly easier than pull-up for most due to bicep addition.",
    category: "Upper Pull",
  },
  {
    name: "Barbell Bent-Over Row",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboids", "Middle Trapezius"],
    secondaryMuscles: ["Biceps Brachii", "Posterior Deltoid", "Erector Spinae"],
    movementPattern: "Horizontal Pull",
    difficulty: "Intermediate",
    equipment: "Barbell",
    biomechanicalNote: "Hip-hinge position creates high erector spinae isometric demand; bar path to lower sternum (overhand) vs. navel (underhand) shifts lat vs. trap emphasis.",
    category: "Upper Pull",
  },
  {
    name: "Dumbbell Row (Standing, Braced)",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboids"],
    secondaryMuscles: ["Biceps Brachii", "Posterior Deltoid", "Teres Major"],
    movementPattern: "Horizontal Pull",
    difficulty: "Intermediate",
    equipment: "Dumbbell",
    biomechanicalNote: "Greater loading potential than bench-supported version; bracing against thigh or rack reduces lumbar shear while maintaining free scapular movement.",
    category: "Upper Pull",
  },
  {
    name: "T-Bar Row",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboids", "Middle Trapezius"],
    secondaryMuscles: ["Biceps Brachii", "Erector Spinae", "Posterior Deltoid"],
    movementPattern: "Horizontal Pull",
    difficulty: "Intermediate",
    equipment: "T-Bar Row Machine or Landmine",
    biomechanicalNote: "Neutral grip with converging handles allows heavy loading while reducing wrist and elbow pronation stress compared to barbell rows.",
    category: "Upper Pull",
  },
  {
    name: "Straight-Arm Lat Pulldown (Cable)",
    primaryMuscles: ["Latissimus Dorsi"],
    secondaryMuscles: ["Teres Major", "Long Head of Triceps", "Posterior Deltoid"],
    movementPattern: "Vertical Pull",
    difficulty: "Intermediate",
    equipment: "Cable Machine",
    biomechanicalNote: "Elbow-locked position removes bicep contribution entirely, isolating lat function through shoulder extension — effective for mind-muscle connection.",
    category: "Upper Pull",
  },
  {
    name: "Incline Dumbbell Curl",
    primaryMuscles: ["Biceps Brachii (long head)"],
    secondaryMuscles: ["Brachialis"],
    movementPattern: "Vertical Pull",
    difficulty: "Intermediate",
    equipment: "Dumbbells, Incline Bench",
    biomechanicalNote: "Shoulder extension on incline places long head in a stretched starting position, increasing peak tension and hypertrophy stimulus.",
    category: "Upper Pull",
  },
  {
    name: "Hammer Curl (Standing)",
    primaryMuscles: ["Brachialis", "Brachioradialis"],
    secondaryMuscles: ["Biceps Brachii"],
    movementPattern: "Vertical Pull",
    difficulty: "Intermediate",
    equipment: "Dumbbells",
    biomechanicalNote: "Neutral forearm position shifts load from biceps brachii to brachialis — the deeper, stronger elbow flexor — and brachioradialis.",
    category: "Upper Pull",
  },
  {
    name: "Barbell Bicep Curl",
    primaryMuscles: ["Biceps Brachii"],
    secondaryMuscles: ["Brachialis", "Brachioradialis"],
    movementPattern: "Vertical Pull",
    difficulty: "Intermediate",
    equipment: "Barbell",
    biomechanicalNote: "Bilateral loading allows heaviest absolute bicep stimulus; fixed supination throughout range maximises bicep mechanical advantage.",
    category: "Upper Pull",
  },
  {
    name: "Dumbbell Rear Delt Fly (Prone Incline)",
    primaryMuscles: ["Posterior Deltoid"],
    secondaryMuscles: ["Infraspinatus", "Teres Minor", "Middle Trapezius", "Rhomboids"],
    movementPattern: "Horizontal Pull",
    difficulty: "Intermediate",
    equipment: "Dumbbells, Incline Bench",
    biomechanicalNote: "Prone position eliminates trunk compensation; fly arc at 90° abduction targets posterior deltoid at peak length-tension curve.",
    category: "Upper Pull",
  },

  // ── Advanced ─────────────────────────────────────────────────────────────────

  {
    name: "Weighted Pull-Up",
    primaryMuscles: ["Latissimus Dorsi"],
    secondaryMuscles: ["Biceps Brachii", "Teres Major", "Rear Deltoid", "Core"],
    movementPattern: "Vertical Pull",
    difficulty: "Advanced",
    equipment: "Pull-Up Bar, Weight Belt",
    biomechanicalNote: "External load amplifies glenohumeral distraction force at bottom position; requires strong rotator cuff and scapular stabiliser base before loading.",
    category: "Upper Pull",
  },
  {
    name: "Barbell Pendlay Row",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboids", "Middle Trapezius"],
    secondaryMuscles: ["Biceps Brachii", "Erector Spinae", "Rear Deltoid"],
    movementPattern: "Horizontal Pull",
    difficulty: "Advanced",
    equipment: "Barbell",
    biomechanicalNote: "Dead-stop from floor each rep eliminates elastic rebound, requiring full concentric force production from a static position — highest power output of row variations.",
    category: "Upper Pull",
  },
  {
    name: "Chest-Supported Barbell Row (Incline Bench)",
    primaryMuscles: ["Rhomboids", "Middle Trapezius", "Latissimus Dorsi"],
    secondaryMuscles: ["Biceps Brachii", "Posterior Deltoid"],
    movementPattern: "Horizontal Pull",
    difficulty: "Advanced",
    equipment: "Barbell, Incline Bench",
    biomechanicalNote: "Prone chest support fully eliminates spinal loading, allowing maximal back musculature stimulus without erector fatigue limiting reps.",
    category: "Upper Pull",
  },
  {
    name: "Single-Arm Cable Row (Standing)",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboids"],
    secondaryMuscles: ["Biceps Brachii", "Core (anti-rotation)", "Posterior Deltoid"],
    movementPattern: "Horizontal Pull",
    difficulty: "Advanced",
    equipment: "Cable Machine",
    biomechanicalNote: "Standing unilateral row creates rotational torque requiring oblique and contralateral lat co-contraction — bridges strength training and functional stability.",
    category: "Upper Pull",
  },
  {
    name: "Archer Pull-Up",
    primaryMuscles: ["Latissimus Dorsi (unilateral emphasis)"],
    secondaryMuscles: ["Biceps Brachii", "Teres Major", "Core"],
    movementPattern: "Vertical Pull",
    difficulty: "Advanced",
    equipment: "Pull-Up Bar",
    biomechanicalNote: "Lateral offset shifts majority of load to one side; direct regression for one-arm pull-up requiring significant unilateral lat and elbow flexor strength.",
    category: "Upper Pull",
  },
  {
    name: "Cable Bayesian Curl",
    primaryMuscles: ["Biceps Brachii (long head)"],
    secondaryMuscles: ["Brachialis"],
    movementPattern: "Vertical Pull",
    difficulty: "Advanced",
    equipment: "Cable Machine",
    biomechanicalNote: "Cable behind the body with shoulder in extension stretches the long head at the initiation point — highest peak stretch tension of any curl variation.",
    category: "Upper Pull",
  },
  {
    name: "Meadows Row (Landmine)",
    primaryMuscles: ["Latissimus Dorsi", "Teres Major"],
    secondaryMuscles: ["Rear Deltoid", "Rhomboids", "Biceps Brachii"],
    movementPattern: "Horizontal Pull",
    difficulty: "Advanced",
    equipment: "Barbell, Landmine Attachment",
    biomechanicalNote: "Perpendicular stance to barbell creates a high lat stretch at initiation; arc pull path matches lat line of pull better than straight horizontal rows.",
    category: "Upper Pull",
  },
];

// ─── LOWER BODY — Quad Dominant (20 exercises) ───────────────────────────────

export const lowerQuadExercises: Exercise[] = [

  // ── Beginner ────────────────────────────────────────────────────────────────

  {
    name: "Bodyweight Squat",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Hamstrings", "Core"],
    movementPattern: "Squat",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Foundational bilateral squat pattern; allows focus on knee tracking, hip crease depth, and ankle dorsiflexion range without external load.",
    category: "Lower Quad",
  },
  {
    name: "Goblet Squat",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Core", "Upper Back"],
    movementPattern: "Squat",
    difficulty: "Beginner",
    equipment: "Dumbbell or Kettlebell",
    biomechanicalNote: "Anterior load counterbalance improves upright torso position and facilitates greater depth; excellent teaching tool for hip-width stance mechanics.",
    category: "Lower Quad",
  },
  {
    name: "Leg Press (Machine)",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Hamstrings"],
    movementPattern: "Squat",
    difficulty: "Beginner",
    equipment: "Leg Press Machine",
    biomechanicalNote: "Guided sled eliminates spinal loading and balance demands; foot position adjusts quad vs. glute emphasis — lower and narrower increases quad dominance.",
    category: "Lower Quad",
  },
  {
    name: "Leg Extension (Machine)",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: [],
    movementPattern: "Squat",
    difficulty: "Beginner",
    equipment: "Leg Extension Machine",
    biomechanicalNote: "Open-chain quad isolation through terminal knee extension; highest shear force at 90° flexion — begin with limited range if patellofemoral pain is present.",
    category: "Lower Quad",
  },
  {
    name: "Step-Up (Bodyweight, Low Box)",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Squat",
    difficulty: "Beginner",
    equipment: "Bodyweight, Box or Step",
    biomechanicalNote: "Unilateral load-bearing pattern with low coordination demand; box height determines knee flexion angle and quad vs. glute emphasis.",
    category: "Lower Quad",
  },
  {
    name: "Wall Sit",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Hip Flexors"],
    movementPattern: "Isometric",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Isometric quad hold at 90° knee flexion; safe joint-loading position developing muscular endurance without dynamic loading.",
    category: "Lower Quad",
  },

  // ── Intermediate ─────────────────────────────────────────────────────────────

  {
    name: "Barbell Back Squat (High Bar)",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Hamstrings", "Core", "Spinal Erectors"],
    movementPattern: "Squat",
    difficulty: "Intermediate",
    equipment: "Barbell, Squat Rack",
    biomechanicalNote: "High bar position encourages upright torso and increased knee flexion, maximising quad recruitment; axial spinal load requires robust core bracing.",
    category: "Lower Quad",
  },
  {
    name: "Dumbbell Bulgarian Split Squat",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Hip Flexors"],
    movementPattern: "Squat",
    difficulty: "Intermediate",
    equipment: "Dumbbells, Bench",
    biomechanicalNote: "Rear foot elevation increases front leg hip flexion range and quad stretch; upright torso shifts emphasis toward quad; forward lean shifts toward glutes.",
    category: "Lower Quad",
  },
  {
    name: "Hack Squat (Machine)",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Hamstrings"],
    movementPattern: "Squat",
    difficulty: "Intermediate",
    equipment: "Hack Squat Machine",
    biomechanicalNote: "Fixed foot plate and shoulder padding enables very upright torso, creating high knee flexion angle and strong vastus medialis and lateralis activation.",
    category: "Lower Quad",
  },
  {
    name: "Walking Lunge (Dumbbell)",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Hip Flexors"],
    movementPattern: "Squat",
    difficulty: "Intermediate",
    equipment: "Dumbbells",
    biomechanicalNote: "Dynamic unilateral movement requiring hip flexor flexibility and knee stability through the step cycle; step length modulates quad vs. glute emphasis.",
    category: "Lower Quad",
  },
  {
    name: "Reverse Lunge (Dumbbell)",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Squat",
    difficulty: "Intermediate",
    equipment: "Dumbbells",
    biomechanicalNote: "Stepping backward reduces anterior knee shear force compared to forward lunge; preferred for patellofemoral-sensitive individuals.",
    category: "Lower Quad",
  },
  {
    name: "Dumbbell Step-Up (Loaded, High Box)",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Squat",
    difficulty: "Intermediate",
    equipment: "Dumbbells, Box",
    biomechanicalNote: "Increased box height raises knee flexion angle and quad time-under-tension; avoid push-off from trail leg to maintain unilateral loading integrity.",
    category: "Lower Quad",
  },
  {
    name: "Barbell Front Squat",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Core", "Upper Back", "Spinal Erectors"],
    movementPattern: "Squat",
    difficulty: "Intermediate",
    equipment: "Barbell, Squat Rack",
    biomechanicalNote: "Anterior bar position demands upright torso and significant thoracic extension mobility; naturally limits load but maximises quad and core demand.",
    category: "Lower Quad",
  },

  // ── Advanced ─────────────────────────────────────────────────────────────────

  {
    name: "Barbell Back Squat (Low Bar)",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Spinal Erectors"],
    movementPattern: "Squat",
    difficulty: "Advanced",
    equipment: "Barbell, Squat Rack",
    biomechanicalNote: "Lower bar position shifts torso angle increasing posterior chain contribution and reducing knee flexion range; allows heaviest absolute squat loads.",
    category: "Lower Quad",
  },
  {
    name: "Barbell Bulgarian Split Squat",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Hip Flexors"],
    movementPattern: "Squat",
    difficulty: "Advanced",
    equipment: "Barbell, Squat Rack, Bench",
    biomechanicalNote: "Barbell loading significantly increases spinal demand and stabilisation requirement relative to dumbbell version; requires hip flexor flexibility and knee stability.",
    category: "Lower Quad",
  },
  {
    name: "Cyclist Squat (Heels Elevated)",
    primaryMuscles: ["Quadriceps (vastus medialis emphasis)"],
    secondaryMuscles: ["Glutes"],
    movementPattern: "Squat",
    difficulty: "Advanced",
    equipment: "Barbell or Dumbbells, Heel Wedge",
    biomechanicalNote: "Heel elevation dramatically increases dorsiflexion range allowing near-vertical shin angle; highest knee flexion range and VMO activation of all squat variations.",
    category: "Lower Quad",
  },
  {
    name: "Paused Barbell Squat",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Core", "Spinal Erectors"],
    movementPattern: "Squat",
    difficulty: "Advanced",
    equipment: "Barbell, Squat Rack",
    biomechanicalNote: "2–3 second pause at depth eliminates stretch-shortening cycle contribution, requiring pure concentric force production and exposing weaknesses in bottom position stability.",
    category: "Lower Quad",
  },
  {
    name: "Single-Leg Leg Press",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Hamstrings"],
    movementPattern: "Squat",
    difficulty: "Advanced",
    equipment: "Leg Press Machine",
    biomechanicalNote: "Unilateral leg press at approximately 60% of bilateral load; exposes asymmetries and develops unilateral quad strength with lower spinal load than split squats.",
    category: "Lower Quad",
  },
  {
    name: "Pistol Squat",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Core", "Hip Flexors", "Ankle Stabilisers"],
    movementPattern: "Squat",
    difficulty: "Advanced",
    equipment: "Bodyweight",
    biomechanicalNote: "Single-leg full-depth squat requiring exceptional ankle dorsiflexion, hip flexor length, and quad eccentric strength; highest balance and coordination demand of all squat variations.",
    category: "Lower Quad",
  },
  {
    name: "Barbell Hack Squat",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Hamstrings", "Core"],
    movementPattern: "Squat",
    difficulty: "Advanced",
    equipment: "Barbell",
    biomechanicalNote: "Bar held behind the legs creates upright torso and strong quad emphasis; technically demanding due to bar path management around the calves during descent.",
    category: "Lower Quad",
  },
];

// ─── LOWER BODY — Hamstring / Glute Dominant (20 exercises) ──────────────────

export const lowerPosteriorExercises: Exercise[] = [

  // ── Beginner ────────────────────────────────────────────────────────────────

  {
    name: "Glute Bridge (Bodyweight)",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Spinal Erectors"],
    movementPattern: "Hinge",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Supine hip extension isolates glute max with minimal spinal compressive load; feet position adjusts hamstring vs. glute contribution.",
    category: "Lower Posterior",
  },
  {
    name: "Hip Thrust (Bodyweight)",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Adductors"],
    movementPattern: "Hinge",
    difficulty: "Beginner",
    equipment: "Bodyweight, Bench",
    biomechanicalNote: "Bench elevation increases hip extension range beyond floor bridge; shoulders-on-bench position allows full posterior pelvic tilt at top for peak glute contraction.",
    category: "Lower Posterior",
  },
  {
    name: "Lying Leg Curl (Machine)",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Gastrocnemius"],
    movementPattern: "Hinge",
    difficulty: "Beginner",
    equipment: "Leg Curl Machine",
    biomechanicalNote: "Prone hip-neutral position allows isolated hamstring knee flexion; plantarflexed ankle reduces gastrocnemius contribution, increasing hamstring isolation.",
    category: "Lower Posterior",
  },
  {
    name: "Seated Leg Curl (Machine)",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Gastrocnemius"],
    movementPattern: "Hinge",
    difficulty: "Beginner",
    equipment: "Seated Leg Curl Machine",
    biomechanicalNote: "Seated hip flexion pre-stretches the hamstrings, increasing active tension through full range; higher peak force at initiation than lying variation.",
    category: "Lower Posterior",
  },
  {
    name: "Romanian Deadlift (Dumbbell)",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Spinal Erectors", "Core", "Adductors"],
    movementPattern: "Hinge",
    difficulty: "Beginner",
    equipment: "Dumbbells",
    biomechanicalNote: "Hip hinge with soft knee bend stretches hamstrings under load; dumbbells at sides reduce spinal compression vs. barbell and allow natural path adjustment.",
    category: "Lower Posterior",
  },
  {
    name: "Cable Kickback",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings"],
    movementPattern: "Hinge",
    difficulty: "Beginner",
    equipment: "Cable Machine, Ankle Strap",
    biomechanicalNote: "Standing hip extension with constant cable tension; knee flexion during extension increases glute max activation by reducing hamstring contribution.",
    category: "Lower Posterior",
  },

  // ── Intermediate ─────────────────────────────────────────────────────────────

  {
    name: "Barbell Hip Thrust",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Adductors", "Quadriceps"],
    movementPattern: "Hinge",
    difficulty: "Intermediate",
    equipment: "Barbell, Bench, Hip Pad",
    biomechanicalNote: "Horizontal force vector aligns optimally with glute max line of pull; allows highest absolute load of any glute isolation exercise.",
    category: "Lower Posterior",
  },
  {
    name: "Barbell Romanian Deadlift",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Spinal Erectors", "Core", "Adductors"],
    movementPattern: "Hinge",
    difficulty: "Intermediate",
    equipment: "Barbell",
    biomechanicalNote: "Bar stays close to legs throughout descent; neutral spine and hip hinge to mid-shin with soft knee — eccentric hamstring load is the primary stimulus.",
    category: "Lower Posterior",
  },
  {
    name: "Conventional Deadlift",
    primaryMuscles: ["Hamstrings", "Glutes", "Spinal Erectors"],
    secondaryMuscles: ["Quadriceps", "Trapezius", "Lats", "Core"],
    movementPattern: "Hinge",
    difficulty: "Intermediate",
    equipment: "Barbell",
    biomechanicalNote: "Full posterior chain compound movement from floor; hip-width stance with bar over mid-foot — highest total systemic loading of any single exercise.",
    category: "Lower Posterior",
  },
  {
    name: "Single-Leg Romanian Deadlift (Dumbbell)",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Core", "Hip Abductors", "Ankle Stabilisers"],
    movementPattern: "Hinge",
    difficulty: "Intermediate",
    equipment: "Dumbbell",
    biomechanicalNote: "Unilateral hip hinge requires transverse plane stability and hip abductor co-contraction; exposes and corrects left-right hamstring asymmetries.",
    category: "Lower Posterior",
  },
  {
    name: "Sumo Deadlift",
    primaryMuscles: ["Glutes", "Hamstrings", "Adductors"],
    secondaryMuscles: ["Quadriceps", "Spinal Erectors", "Trapezius"],
    movementPattern: "Hinge",
    difficulty: "Intermediate",
    equipment: "Barbell",
    biomechanicalNote: "Wide stance and toed-out foot position increases hip adductor and glute contribution; more upright torso reduces lumbar moment arm vs. conventional stance.",
    category: "Lower Posterior",
  },
  {
    name: "Good Morning (Barbell)",
    primaryMuscles: ["Hamstrings", "Spinal Erectors"],
    secondaryMuscles: ["Glutes", "Core", "Adductors"],
    movementPattern: "Hinge",
    difficulty: "Intermediate",
    equipment: "Barbell",
    biomechanicalNote: "Bar on traps with hip hinge creates a long moment arm from load to lumbar spine — must be performed with light load and strict neutral spine.",
    category: "Lower Posterior",
  },
  {
    name: "Nordic Hamstring Curl",
    primaryMuscles: ["Hamstrings (eccentric emphasis)"],
    secondaryMuscles: ["Glutes", "Gastrocnemius"],
    movementPattern: "Hinge",
    difficulty: "Intermediate",
    equipment: "Bodyweight, Anchor Point",
    biomechanicalNote: "Highest eccentric hamstring force production of any exercise; strong evidence for ACL and hamstring strain injury prevention in athletic populations.",
    category: "Lower Posterior",
  },

  // ── Advanced ─────────────────────────────────────────────────────────────────

  {
    name: "Single-Leg Hip Thrust (Barbell)",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Adductors"],
    movementPattern: "Hinge",
    difficulty: "Advanced",
    equipment: "Barbell, Bench, Hip Pad",
    biomechanicalNote: "Unilateral hip thrust doubles per-leg glute demand; requires contralateral pelvis stabilisation through hip abductors to prevent pelvic drop.",
    category: "Lower Posterior",
  },
  {
    name: "Glute-Ham Raise",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Gastrocnemius", "Spinal Erectors", "Core"],
    movementPattern: "Hinge",
    difficulty: "Advanced",
    equipment: "Glute-Ham Raise Machine",
    biomechanicalNote: "Combines knee flexion and hip extension in a single movement, loading hamstrings as both hip extensor and knee flexor simultaneously — highest hamstring co-contraction demand.",
    category: "Lower Posterior",
  },
  {
    name: "Single-Leg Romanian Deadlift (Barbell)",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Core", "Hip Abductors", "Spinal Erectors"],
    movementPattern: "Hinge",
    difficulty: "Advanced",
    equipment: "Barbell",
    biomechanicalNote: "Barbell load increases rotational torque in the frontal plane relative to dumbbell variation; requires highly developed hip abductor strength to maintain pelvis level.",
    category: "Lower Posterior",
  },
  {
    name: "Deficit Romanian Deadlift",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Spinal Erectors", "Core", "Adductors"],
    movementPattern: "Hinge",
    difficulty: "Advanced",
    equipment: "Barbell, Deficit Platform",
    biomechanicalNote: "Standing on a 2–4 inch platform increases hamstring range of motion at bottom; greatest peak hamstring stretch of any deadlift variation.",
    category: "Lower Posterior",
  },
  {
    name: "45° Back Extension (Loaded)",
    primaryMuscles: ["Spinal Erectors", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    movementPattern: "Hinge",
    difficulty: "Advanced",
    equipment: "Back Extension Bench, Weight Plate or Barbell",
    biomechanicalNote: "Hip hinge on 45° bench with load at chest or across traps — foot position modulates glute vs. erector emphasis; high lumbar extension endurance demand.",
    category: "Lower Posterior",
  },
  {
    name: "Banded Hip Thrust (Accommodating Resistance)",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Adductors", "Core"],
    movementPattern: "Hinge",
    difficulty: "Advanced",
    equipment: "Barbell, Resistance Band, Bench",
    biomechanicalNote: "Band adds ascending resistance that peaks at full hip extension — matches glute force-length curve better than barbell alone, increasing peak contraction stimulus.",
    category: "Lower Posterior",
  },
  {
    name: "Trap Bar Deadlift",
    primaryMuscles: ["Glutes", "Hamstrings", "Quadriceps"],
    secondaryMuscles: ["Spinal Erectors", "Trapezius", "Core"],
    movementPattern: "Hinge",
    difficulty: "Advanced",
    equipment: "Trap Bar",
    biomechanicalNote: "Neutral grip handles and centre-of-mass load alignment reduce lumbar moment arm vs. straight bar; higher knee flexion angle increases quad contribution relative to conventional deadlift.",
    category: "Lower Posterior",
  },
];

// ─── CORE — Anterior / Posterior / Rotational / Anti-Rotation (22 exercises) ─

export const coreExercises: Exercise[] = [

  // ── Beginner ────────────────────────────────────────────────────────────────

  {
    name: "Dead Bug",
    primaryMuscles: ["Transverse Abdominis", "Rectus Abdominis"],
    secondaryMuscles: ["Hip Flexors", "Spinal Erectors"],
    movementPattern: "Anti-Rotation",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Contralateral limb extension while maintaining lumbar contact trains deep abdominal co-contraction and inter-limb coordination without spinal flexion.",
    category: "Core",
  },
  {
    name: "Plank (Standard)",
    primaryMuscles: ["Transverse Abdominis", "Rectus Abdominis"],
    secondaryMuscles: ["Glutes", "Spinal Erectors", "Serratus Anterior", "Shoulder Stabilisers"],
    movementPattern: "Isometric",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Prone isometric hold requiring whole-system co-contraction; neutral spine position with posterior pelvic tilt cue prevents lumbar hyperextension compensation.",
    category: "Core",
  },
  {
    name: "Bird Dog",
    primaryMuscles: ["Spinal Erectors", "Glutes"],
    secondaryMuscles: ["Transverse Abdominis", "Shoulder Stabilisers"],
    movementPattern: "Stability",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Quadruped contralateral extension trains lumbopelvic stability and spinal extensor endurance; part of McGill's evidence-based Big Three for spine health.",
    category: "Core",
  },
  {
    name: "McGill Curl-Up",
    primaryMuscles: ["Rectus Abdominis"],
    secondaryMuscles: ["Transverse Abdominis"],
    movementPattern: "Isometric",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Partial trunk lift with hands under lumbar spine preserves natural lordosis; avoids full spinal flexion making it joint-safe while training abdominal endurance.",
    category: "Core",
  },
  {
    name: "Side Plank (Standard)",
    primaryMuscles: ["Obliques", "Quadratus Lumborum"],
    secondaryMuscles: ["Glutes", "Hip Abductors", "Shoulder Stabilisers"],
    movementPattern: "Anti-Rotation",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Lateral isometric hold trains frontal-plane spinal stability; part of McGill's Big Three — hip adductor contribution varies with foot stacking position.",
    category: "Core",
  },
  {
    name: "Superman Hold",
    primaryMuscles: ["Spinal Erectors", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Posterior Deltoid", "Rhomboids"],
    movementPattern: "Isometric",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Prone spinal extension isometric; develops posterior chain endurance with no compressive load — appropriate entry point for spinal extensor training.",
    category: "Core",
  },

  // ── Intermediate ─────────────────────────────────────────────────────────────

  {
    name: "Hollow Body Hold",
    primaryMuscles: ["Rectus Abdominis", "Transverse Abdominis"],
    secondaryMuscles: ["Hip Flexors", "Serratus Anterior"],
    movementPattern: "Isometric",
    difficulty: "Intermediate",
    equipment: "Bodyweight",
    biomechanicalNote: "Full posterior pelvic tilt with limbs extended creates maximum lever arm for abdominal isometric demand; foundation of gymnastics strength training.",
    category: "Core",
  },
  {
    name: "Ab Wheel Rollout (Kneeling)",
    primaryMuscles: ["Rectus Abdominis", "Transverse Abdominis"],
    secondaryMuscles: ["Latissimus Dorsi", "Triceps", "Serratus Anterior"],
    movementPattern: "Anti-Rotation",
    difficulty: "Intermediate",
    equipment: "Ab Wheel",
    biomechanicalNote: "Rollout extends moment arm progressively, requiring anti-extension abdominal strength; lat engagement at initiation is critical to prevent lumbar hyperextension.",
    category: "Core",
  },
  {
    name: "Cable Crunch (Kneeling)",
    primaryMuscles: ["Rectus Abdominis"],
    secondaryMuscles: ["Obliques"],
    movementPattern: "Rotation",
    difficulty: "Intermediate",
    equipment: "Cable Machine",
    biomechanicalNote: "Constant cable tension maintains load at shortened position unlike bodyweight crunches; hip hinge must be avoided to isolate trunk flexion.",
    category: "Core",
  },
  {
    name: "Pallof Press (Standing)",
    primaryMuscles: ["Obliques", "Transverse Abdominis"],
    secondaryMuscles: ["Glutes", "Hip Abductors", "Shoulder Stabilisers"],
    movementPattern: "Anti-Rotation",
    difficulty: "Intermediate",
    equipment: "Cable Machine or Resistance Band",
    biomechanicalNote: "Horizontal cable press with lateral load creates rotational torque resisted isometrically; trains anti-rotation stiffness essential for force transfer in athletic movement.",
    category: "Core",
  },
  {
    name: "Cable Wood Chop (High-to-Low)",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Transverse Abdominis", "Shoulder Girdle", "Hip Rotators"],
    movementPattern: "Rotation",
    difficulty: "Intermediate",
    equipment: "Cable Machine",
    biomechanicalNote: "Diagonal rotational pattern from high pulley trains oblique force production in the transverse plane; mimics the deceleration demands of throwing and swinging.",
    category: "Core",
  },
  {
    name: "Cable Wood Chop (Low-to-High)",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Transverse Abdominis", "Hip Rotators", "Shoulder Girdle"],
    movementPattern: "Rotation",
    difficulty: "Intermediate",
    equipment: "Cable Machine",
    biomechanicalNote: "Upward diagonal chop preferentially loads the lower obliques and hip rotators; complements high-to-low variation to train full rotational power range.",
    category: "Core",
  },
  {
    name: "Hanging Knee Raise",
    primaryMuscles: ["Rectus Abdominis", "Hip Flexors"],
    secondaryMuscles: ["Transverse Abdominis", "Forearm Flexors"],
    movementPattern: "Rotation",
    difficulty: "Intermediate",
    equipment: "Pull-Up Bar",
    biomechanicalNote: "Hanging position removes spinal compressive load; knee tuck reduces hip flexor moment arm making this the appropriate regression before straight-leg raise.",
    category: "Core",
  },
  {
    name: "Suitcase Carry (Single-Arm)",
    primaryMuscles: ["Quadratus Lumborum", "Obliques"],
    secondaryMuscles: ["Trapezius", "Glutes", "Hip Abductors", "Core"],
    movementPattern: "Anti-Rotation",
    difficulty: "Intermediate",
    equipment: "Dumbbell or Kettlebell",
    biomechanicalNote: "Lateral load during gait requires constant frontal-plane stabilisation; one of the most functionally transferable core exercises due to real-world loading pattern.",
    category: "Core",
  },
  {
    name: "Russian Twist (Weighted)",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Rectus Abdominis", "Hip Flexors", "Transverse Abdominis"],
    movementPattern: "Rotation",
    difficulty: "Intermediate",
    equipment: "Weight Plate or Medicine Ball",
    biomechanicalNote: "Seated trunk rotation with load; feet elevated increases hip flexor demand — reduce hip flexor dominance by keeping feet grounded when targeting obliques specifically.",
    category: "Core",
  },

  // ── Advanced ─────────────────────────────────────────────────────────────────

  {
    name: "Hanging Straight-Leg Raise",
    primaryMuscles: ["Rectus Abdominis", "Hip Flexors"],
    secondaryMuscles: ["Transverse Abdominis", "Obliques"],
    movementPattern: "Rotation",
    difficulty: "Advanced",
    equipment: "Pull-Up Bar",
    biomechanicalNote: "Extended knee dramatically increases hip flexor and lower abdominal moment arm; posterior pelvic tilt at top required to achieve full rectus abdominis shortening.",
    category: "Core",
  },
  {
    name: "Ab Wheel Rollout (Standing)",
    primaryMuscles: ["Rectus Abdominis", "Transverse Abdominis"],
    secondaryMuscles: ["Latissimus Dorsi", "Triceps", "Serratus Anterior"],
    movementPattern: "Anti-Rotation",
    difficulty: "Advanced",
    equipment: "Ab Wheel",
    biomechanicalNote: "Standing start multiplies anti-extension demand; full rollout to horizontal requires near-elite anterior core strength and lat engagement to prevent lumbar collapse.",
    category: "Core",
  },
  {
    name: "Copenhagen Plank",
    primaryMuscles: ["Hip Adductors", "Obliques"],
    secondaryMuscles: ["Quadratus Lumborum", "Glutes", "Core"],
    movementPattern: "Anti-Rotation",
    difficulty: "Advanced",
    equipment: "Bodyweight, Bench",
    biomechanicalNote: "Side-lying position with top foot on bench loads hip adductors as primary lateral stabilisers — highly effective for groin injury prevention in lateral-movement sports.",
    category: "Core",
  },
  {
    name: "Landmine Rotation",
    primaryMuscles: ["Obliques", "Transverse Abdominis"],
    secondaryMuscles: ["Shoulder Girdle", "Hip Rotators", "Glutes"],
    movementPattern: "Rotation",
    difficulty: "Advanced",
    equipment: "Barbell, Landmine Attachment",
    biomechanicalNote: "Arc press path creates coupled rotation and shoulder flexion; develops rotational power through full kinetic chain in a joint-friendly arc trajectory.",
    category: "Core",
  },
  {
    name: "Dragon Flag",
    primaryMuscles: ["Rectus Abdominis", "Transverse Abdominis"],
    secondaryMuscles: ["Hip Flexors", "Spinal Erectors", "Glutes"],
    movementPattern: "Isometric",
    difficulty: "Advanced",
    equipment: "Bodyweight, Bench",
    biomechanicalNote: "Full-body lever from fixed shoulders demands extreme anti-extension abdominal strength; eccentric lowering under control is the primary training stimulus.",
    category: "Core",
  },
  {
    name: "Half-Kneeling Cable Chop",
    primaryMuscles: ["Obliques", "Transverse Abdominis"],
    secondaryMuscles: ["Hip Stabilisers", "Shoulder Girdle", "Glutes"],
    movementPattern: "Rotation",
    difficulty: "Advanced",
    equipment: "Cable Machine",
    biomechanicalNote: "Half-kneeling position eliminates lower-body drive, isolating trunk and hip rotational power; tests rotational stability asymmetry between left and right sides.",
    category: "Core",
  },
];

// ─── FULL BODY — Compound Athletic Movements (22 exercises) ──────────────────

export const fullBodyExercises: Exercise[] = [

  // ── Beginner ────────────────────────────────────────────────────────────────

  {
    name: "Kettlebell Swing (Two-Hand)",
    primaryMuscles: ["Glutes", "Hamstrings"],
    secondaryMuscles: ["Spinal Erectors", "Core", "Shoulder Girdle", "Quadriceps"],
    movementPattern: "Explosive",
    difficulty: "Beginner",
    equipment: "Kettlebell",
    biomechanicalNote: "Ballistic hip hinge teaching explosive posterior chain drive; the bell is projected by hip extension, not arm elevation — critical coaching cue.",
    category: "Full Body",
  },
  {
    name: "Dumbbell Goblet Squat to Press",
    primaryMuscles: ["Quadriceps", "Glutes", "Shoulder Girdle"],
    secondaryMuscles: ["Core", "Triceps", "Hamstrings"],
    movementPattern: "Explosive",
    difficulty: "Beginner",
    equipment: "Dumbbell",
    biomechanicalNote: "Squat-to-press combination links lower and upper body force production in one fluid movement; anterior load facilitates upright torso during squat phase.",
    category: "Full Body",
  },
  {
    name: "Dumbbell Thruster",
    primaryMuscles: ["Quadriceps", "Glutes", "Anterior Deltoid"],
    secondaryMuscles: ["Hamstrings", "Triceps", "Core"],
    movementPattern: "Explosive",
    difficulty: "Beginner",
    equipment: "Dumbbells",
    biomechanicalNote: "Front-racked squat to overhead press uses hip drive to initiate the press, reducing shoulder-only load and increasing total power output.",
    category: "Full Body",
  },
  {
    name: "Medicine Ball Slam",
    primaryMuscles: ["Latissimus Dorsi", "Core", "Glutes"],
    secondaryMuscles: ["Shoulder Girdle", "Hip Flexors", "Quadriceps"],
    movementPattern: "Explosive",
    difficulty: "Beginner",
    equipment: "Medicine Ball",
    biomechanicalNote: "Full-body overhead-to-floor power expression; trains triple extension on the upswing and rapid eccentric deceleration on the slam — useful for power development without Olympic lift technique.",
    category: "Full Body",
  },
  {
    name: "Battle Ropes (Alternating Waves)",
    primaryMuscles: ["Shoulder Girdle", "Core"],
    secondaryMuscles: ["Biceps", "Triceps", "Glutes", "Quadriceps"],
    movementPattern: "Explosive",
    difficulty: "Beginner",
    equipment: "Battle Ropes",
    biomechanicalNote: "Continuous alternating wave pattern develops shoulder endurance and cardiovascular conditioning with low joint-compressive load; stance and hinge depth modulate lower body involvement.",
    category: "Full Body",
  },

  // ── Intermediate ─────────────────────────────────────────────────────────────

  {
    name: "Kettlebell Turkish Get-Up",
    primaryMuscles: ["Shoulder Stabilisers", "Core", "Glutes"],
    secondaryMuscles: ["Quadriceps", "Hip Abductors", "Triceps"],
    movementPattern: "Stability",
    difficulty: "Intermediate",
    equipment: "Kettlebell",
    biomechanicalNote: "Multi-phase ground-to-standing movement with overhead load; tests shoulder stability through full range of motion and requires sequential hip, core, and shoulder control.",
    category: "Full Body",
  },
  {
    name: "Kettlebell Swing (Single-Arm)",
    primaryMuscles: ["Glutes", "Hamstrings"],
    secondaryMuscles: ["Core (anti-rotation)", "Shoulder Girdle", "Spinal Erectors"],
    movementPattern: "Explosive",
    difficulty: "Intermediate",
    equipment: "Kettlebell",
    biomechanicalNote: "Unilateral swing creates rotational torque requiring oblique and contralateral lat co-contraction; higher anti-rotation demand than two-hand variation.",
    category: "Full Body",
  },
  {
    name: "Dumbbell Clean and Press",
    primaryMuscles: ["Glutes", "Hamstrings", "Anterior Deltoid"],
    secondaryMuscles: ["Quadriceps", "Trapezius", "Core", "Triceps"],
    movementPattern: "Explosive",
    difficulty: "Intermediate",
    equipment: "Dumbbells",
    biomechanicalNote: "Hang position clean into overhead press; teaches triple extension (ankle, knee, hip) and transitions into pressing without a rack, making it accessible for home training.",
    category: "Full Body",
  },
  {
    name: "Barbell Thruster",
    primaryMuscles: ["Quadriceps", "Glutes", "Anterior Deltoid"],
    secondaryMuscles: ["Hamstrings", "Triceps", "Core", "Trapezius"],
    movementPattern: "Explosive",
    difficulty: "Intermediate",
    equipment: "Barbell",
    biomechanicalNote: "Front-racked barbell squat-to-press; most metabolically demanding single-implement exercise due to large muscle mass involvement and ballistic push-press finishing position.",
    category: "Full Body",
  },
  {
    name: "Box Jump",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    movementPattern: "Explosive",
    difficulty: "Intermediate",
    equipment: "Plyometric Box",
    biomechanicalNote: "Bilateral explosive jump onto box trains rate of force development; landing mechanics — soft knees, hip hinge — are the primary injury-prevention focus.",
    category: "Full Body",
  },
  {
    name: "Broad Jump",
    primaryMuscles: ["Glutes", "Quadriceps", "Hamstrings"],
    secondaryMuscles: ["Calves", "Core", "Hip Flexors"],
    movementPattern: "Explosive",
    difficulty: "Intermediate",
    equipment: "Bodyweight",
    biomechanicalNote: "Horizontal power expression requiring coordinated triple extension and arm drive; distance reflects lower body power output and is a valid field performance metric.",
    category: "Full Body",
  },
  {
    name: "Sled Push",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core", "Shoulder Girdle"],
    movementPattern: "Explosive",
    difficulty: "Intermediate",
    equipment: "Sled",
    biomechanicalNote: "Horizontal force production against external resistance with no eccentric phase — negligible DOMS, allowing frequent use; load and velocity inversely determine speed-strength vs. strength-speed emphasis.",
    category: "Full Body",
  },
  {
    name: "Farmers Carry (Heavy, Bilateral)",
    primaryMuscles: ["Trapezius", "Core", "Glutes"],
    secondaryMuscles: ["Forearm Flexors", "Quadriceps", "Shoulder Girdle"],
    movementPattern: "Carry",
    difficulty: "Intermediate",
    equipment: "Dumbbells, Kettlebells, or Farmer's Walk Handles",
    biomechanicalNote: "Loaded walking with heavy bilateral hold trains whole-system postural stability, grip strength, and cardiovascular conditioning simultaneously.",
    category: "Full Body",
  },

  // ── Advanced ─────────────────────────────────────────────────────────────────

  {
    name: "Barbell Hang Power Clean",
    primaryMuscles: ["Glutes", "Hamstrings", "Trapezius"],
    secondaryMuscles: ["Quadriceps", "Core", "Shoulder Girdle", "Calves"],
    movementPattern: "Explosive",
    difficulty: "Advanced",
    equipment: "Barbell",
    biomechanicalNote: "Hang position reduces first-pull complexity; triple extension followed by elbow turnover and front rack catch trains explosive posterior chain power and upper body receiving mechanics.",
    category: "Full Body",
  },
  {
    name: "Barbell Power Clean (From Floor)",
    primaryMuscles: ["Glutes", "Hamstrings", "Trapezius"],
    secondaryMuscles: ["Quadriceps", "Core", "Spinal Erectors", "Calves"],
    movementPattern: "Explosive",
    difficulty: "Advanced",
    equipment: "Barbell",
    biomechanicalNote: "Full Olympic pull from floor requires precise bar-path management over the knee; highest rate of force development demand of any barbell movement.",
    category: "Full Body",
  },
  {
    name: "Push Press (Barbell)",
    primaryMuscles: ["Anterior Deltoid", "Glutes", "Quadriceps"],
    secondaryMuscles: ["Triceps", "Core", "Trapezius"],
    movementPattern: "Explosive",
    difficulty: "Advanced",
    equipment: "Barbell",
    biomechanicalNote: "Brief dip-and-drive generates lower body momentum transferred to the bar; allows 20–30% greater load overhead than strict press and trains power expression through the kinetic chain.",
    category: "Full Body",
  },
  {
    name: "Barbell Hang Snatch",
    primaryMuscles: ["Glutes", "Hamstrings", "Trapezius", "Shoulder Girdle"],
    secondaryMuscles: ["Quadriceps", "Core", "Triceps", "Calves"],
    movementPattern: "Explosive",
    difficulty: "Advanced",
    equipment: "Barbell",
    biomechanicalNote: "Wide-grip Olympic pull to overhead catch in a single movement; highest power output per kg of any resistance exercise — requires substantial technical proficiency before loading.",
    category: "Full Body",
  },
  {
    name: "Barbell Complex (Pull–Squat–Press)",
    primaryMuscles: ["Glutes", "Hamstrings", "Quadriceps", "Shoulder Girdle"],
    secondaryMuscles: ["Core", "Trapezius", "Biceps", "Triceps"],
    movementPattern: "Explosive",
    difficulty: "Advanced",
    equipment: "Barbell",
    biomechanicalNote: "Sequential deadlift, hang clean, front squat, and push press performed without setting bar down; metabolic and neuromuscular demand is extremely high — load should be limited to weakest movement in the chain.",
    category: "Full Body",
  },
  {
    name: "Kettlebell Snatch",
    primaryMuscles: ["Glutes", "Hamstrings", "Shoulder Girdle"],
    secondaryMuscles: ["Core", "Trapezius", "Rotator Cuff"],
    movementPattern: "Explosive",
    difficulty: "Advanced",
    equipment: "Kettlebell",
    biomechanicalNote: "Single-arm ballistic swing-to-overhead with a continuous arc; high shoulder stability and wrist control demand — the overhead catch requires precise elbow lockout cuing.",
    category: "Full Body",
  },
  {
    name: "Sandbag Clean and Carry",
    primaryMuscles: ["Glutes", "Hamstrings", "Core"],
    secondaryMuscles: ["Quadriceps", "Trapezius", "Shoulder Girdle", "Forearm Flexors"],
    movementPattern: "Carry",
    difficulty: "Advanced",
    equipment: "Sandbag",
    biomechanicalNote: "Unstable shifting load challenges stabilisers not recruited under fixed-implement training; clean to shoulder carry trains full triple extension and asymmetric postural control.",
    category: "Full Body",
  },
  {
    name: "Depth Jump",
    primaryMuscles: ["Quadriceps", "Glutes", "Calves"],
    secondaryMuscles: ["Hamstrings", "Core", "Hip Flexors"],
    movementPattern: "Explosive",
    difficulty: "Advanced",
    equipment: "Plyometric Box",
    biomechanicalNote: "Step-off from box minimises ground contact time and maximises stretch-shortening cycle stimulus; most potent plyometric exercise for reactive strength development — requires solid landing mechanics before use.",
    category: "Full Body",
  },
];

// ─── MOBILITY / STABILITY / PREHAB (21 exercises) ────────────────────────────

export const mobilityExercises: Exercise[] = [

  // ── Hip and Lower Body ────────────────────────────────────────────────────────

  {
    name: "90/90 Hip Rotation",
    primaryMuscles: ["Hip External Rotators", "Hip Internal Rotators"],
    secondaryMuscles: ["Glutes", "Adductors", "TFL"],
    movementPattern: "Mobility",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Seated 90° bilateral hip rotation mobilises both internal and external rotation simultaneously; addresses the most commonly restricted hip motion planes.",
    category: "Mobility",
  },
  {
    name: "World's Greatest Stretch",
    primaryMuscles: ["Hip Flexors", "Hip External Rotators", "Thoracic Spine"],
    secondaryMuscles: ["Hamstrings", "Adductors", "Shoulder Girdle"],
    movementPattern: "Mobility",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Multi-joint lunge-to-rotation sequence addressing hip flexor, adductor, and thoracic mobility in one pattern — widely used as a warm-up standard.",
    category: "Mobility",
  },
  {
    name: "Kneeling Hip Flexor Stretch",
    primaryMuscles: ["Hip Flexors (Iliopsoas)", "Rectus Femoris"],
    secondaryMuscles: ["TFL", "Anterior Capsule"],
    movementPattern: "Mobility",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Half-kneeling position with posterior pelvic tilt maximises iliopsoas elongation; anterior pelvic tilt compensation is the most common error eliminating the stretch.",
    category: "Mobility",
  },
  {
    name: "Cossack Squat",
    primaryMuscles: ["Hip Adductors", "Hip External Rotators"],
    secondaryMuscles: ["Quadriceps", "Hamstrings", "Ankle Dorsiflexors"],
    movementPattern: "Mobility",
    difficulty: "Intermediate",
    equipment: "Bodyweight",
    biomechanicalNote: "Deep lateral lunge with extended opposite leg trains adductor length and lateral hip mobility under load — more functionally demanding than static adductor stretches.",
    category: "Mobility",
  },
  {
    name: "Ankle Dorsiflexion Mobilisation (Wall)",
    primaryMuscles: ["Ankle Dorsiflexors", "Gastrocnemius"],
    secondaryMuscles: ["Soleus", "Ankle Joint Capsule"],
    movementPattern: "Mobility",
    difficulty: "Beginner",
    equipment: "Bodyweight, Wall",
    biomechanicalNote: "Knee-to-wall test and mobilisation; restricted dorsiflexion is a primary driver of squat compensations including heel rise and forward torso collapse.",
    category: "Mobility",
  },
  {
    name: "Single-Leg Balance (Static)",
    primaryMuscles: ["Hip Abductors", "Ankle Stabilisers"],
    secondaryMuscles: ["Glutes", "Core", "Peroneals"],
    movementPattern: "Stability",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Static unipedal balance trains proprioception and vestibular system; eyes-closed variation increases difficulty by removing visual stabilisation cues.",
    category: "Mobility",
  },
  {
    name: "Pigeon Pose",
    primaryMuscles: ["Hip External Rotators", "Piriformis", "Glute Medius"],
    secondaryMuscles: ["Hip Flexors", "Adductors"],
    movementPattern: "Mobility",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Deep external rotation stretch targeting posterior hip capsule; pain on direct pressure to piriformis may indicate sciatic involvement — modify to figure-four if so.",
    category: "Mobility",
  },
  {
    name: "Y-Balance Reach",
    primaryMuscles: ["Hip Stabilisers", "Core", "Ankle Stabilisers"],
    secondaryMuscles: ["Glutes", "Hamstrings", "Peroneals"],
    movementPattern: "Stability",
    difficulty: "Intermediate",
    equipment: "Bodyweight",
    biomechanicalNote: "Single-leg stance with maximal reach in anterior, posteromedial, and posterolateral directions; asymmetry score is predictive of lower extremity injury risk.",
    category: "Mobility",
  },

  // ── Shoulder and Upper Body ───────────────────────────────────────────────────

  {
    name: "Band Pull-Apart",
    primaryMuscles: ["Posterior Deltoid", "Rhomboids", "Middle Trapezius"],
    secondaryMuscles: ["Infraspinatus", "Teres Minor"],
    movementPattern: "Mobility",
    difficulty: "Beginner",
    equipment: "Resistance Band",
    biomechanicalNote: "Horizontal abduction with band trains posterior shoulder musculature often undertrained relative to pressing; essential counter-movement for bench-heavy programming.",
    category: "Mobility",
  },
  {
    name: "Wall Slide",
    primaryMuscles: ["Serratus Anterior", "Lower Trapezius"],
    secondaryMuscles: ["Rotator Cuff", "Upper Trapezius (inhibition target)"],
    movementPattern: "Mobility",
    difficulty: "Beginner",
    equipment: "Bodyweight, Wall",
    biomechanicalNote: "Overhead arm slide against wall trains upward scapular rotation and serratus activation while reducing upper trapezius dominance — key for shoulder impingement prevention.",
    category: "Mobility",
  },
  {
    name: "Shoulder Dislocate (Band)",
    primaryMuscles: ["Shoulder Capsule", "Posterior Deltoid"],
    secondaryMuscles: ["Pectorals", "Biceps", "Triceps"],
    movementPattern: "Mobility",
    difficulty: "Intermediate",
    equipment: "Resistance Band",
    biomechanicalNote: "Full overhead arc with wide band grip progressively improves glenohumeral and scapular mobility through range; width should be set so no compensation or pain occurs.",
    category: "Mobility",
  },
  {
    name: "Thoracic Rotation (Foam Roller)",
    primaryMuscles: ["Thoracic Spine Rotators"],
    secondaryMuscles: ["Latissimus Dorsi", "Obliques"],
    movementPattern: "Mobility",
    difficulty: "Beginner",
    equipment: "Foam Roller",
    biomechanicalNote: "Foam roller under thoracic spine with supported rotation mobilises the most commonly restricted spinal segment; lumbar spine should remain passive throughout.",
    category: "Mobility",
  },
  {
    name: "Side-Lying External Rotation",
    primaryMuscles: ["Infraspinatus", "Teres Minor"],
    secondaryMuscles: ["Posterior Deltoid"],
    movementPattern: "Stability",
    difficulty: "Beginner",
    equipment: "Dumbbell",
    biomechanicalNote: "Side-lying position with elbow at 90° isolates glenohumeral external rotation; the most direct strengthening exercise for rotator cuff external rotators.",
    category: "Mobility",
  },
  {
    name: "Wall Angel",
    primaryMuscles: ["Lower Trapezius", "Serratus Anterior"],
    secondaryMuscles: ["Rhomboids", "Posterior Deltoid", "Rotator Cuff"],
    movementPattern: "Mobility",
    difficulty: "Intermediate",
    equipment: "Bodyweight, Wall",
    biomechanicalNote: "Full-contact overhead arm slide against wall simultaneously tests thoracic extension, shoulder flexion, and scapular upward rotation — reveals the most common upper body mobility deficiencies.",
    category: "Mobility",
  },

  // ── Spine and Full-Chain ──────────────────────────────────────────────────────

  {
    name: "Cat-Cow",
    primaryMuscles: ["Spinal Extensors", "Abdominals"],
    secondaryMuscles: ["Hip Flexors", "Shoulder Girdle"],
    movementPattern: "Mobility",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Rhythmic spinal flexion-extension mobilises all lumbar and thoracic segments; breathing synchronisation (exhale-flex, inhale-extend) enhances range and parasympathetic activation.",
    category: "Mobility",
  },
  {
    name: "Quadruped Rock Back",
    primaryMuscles: ["Hip Flexors", "Lumbar Spine"],
    secondaryMuscles: ["Glutes", "Thoracic Spine"],
    movementPattern: "Mobility",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Heel-to-glute rock in quadruped position mobilises hip flexion range while maintaining spinal neutrality; reveals hip flexor restriction limiting squat depth.",
    category: "Mobility",
  },
  {
    name: "Thread-the-Needle",
    primaryMuscles: ["Thoracic Spine Rotators"],
    secondaryMuscles: ["Shoulder Girdle", "Obliques"],
    movementPattern: "Mobility",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Quadruped unilateral thoracic rotation with arm thread targets mid-thoracic rotation mobility; one of the most effective movements for isolated thoracic segment mobilisation.",
    category: "Mobility",
  },
  {
    name: "Jefferson Curl",
    primaryMuscles: ["Spinal Flexors", "Hamstrings"],
    secondaryMuscles: ["Spinal Erectors (eccentric lengthening)", "Glutes"],
    movementPattern: "Mobility",
    difficulty: "Intermediate",
    equipment: "Light Dumbbell or Barbell",
    biomechanicalNote: "Controlled segmental spinal flexion under minimal load trains spinal erector length and intervertebral mobility; must begin with bodyweight only and progress load extremely conservatively.",
    category: "Mobility",
  },
  {
    name: "Thoracic Extension Over Foam Roller",
    primaryMuscles: ["Thoracic Spine Extensors"],
    secondaryMuscles: ["Intercostals", "Shoulder Girdle"],
    movementPattern: "Mobility",
    difficulty: "Beginner",
    equipment: "Foam Roller",
    biomechanicalNote: "Passive thoracic extension over roller reverses the flexion bias of prolonged sitting; segment-by-segment extension from T4–T10 produces greatest range improvement.",
    category: "Mobility",
  },
  {
    name: "Lateral Band Walk",
    primaryMuscles: ["Glute Medius", "Hip Abductors"],
    secondaryMuscles: ["TFL", "Quadriceps", "Ankle Stabilisers"],
    movementPattern: "Stability",
    difficulty: "Beginner",
    equipment: "Resistance Band",
    biomechanicalNote: "Lateral stepping with band above knees activates glute medius in the frontal plane — the most clinically used exercise for IT band syndrome and patellofemoral pain prevention.",
    category: "Mobility",
  },
  {
    name: "Seated Thoracic Rotation (Open Book)",
    primaryMuscles: ["Thoracic Spine Rotators"],
    secondaryMuscles: ["Obliques", "Posterior Shoulder"],
    movementPattern: "Mobility",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    biomechanicalNote: "Side-lying stacked-knee position locks out lumbar rotation, isolating thoracic spine mobility; the degree of shoulder blade contact with floor is a simple rotation assessment.",
    category: "Mobility",
  },
];

// ─── COMBINED EXPORTS ─────────────────────────────────────────────────────────

export const allExercises: Exercise[] = [
  ...upperPushExercises,
  ...upperPullExercises,
  ...lowerQuadExercises,
  ...lowerPosteriorExercises,
  ...coreExercises,
  ...fullBodyExercises,
  ...mobilityExercises,
];

export const exercisesByCategory: Record<MuscleCategory, Exercise[]> = {
  "Upper Push":      upperPushExercises,
  "Upper Pull":      upperPullExercises,
  "Lower Quad":      lowerQuadExercises,
  "Lower Posterior": lowerPosteriorExercises,
  "Core":            coreExercises,
  "Full Body":       fullBodyExercises,
  "Mobility":        mobilityExercises,
};

export const exercisesByDifficulty: Record<DifficultyLevel, Exercise[]> = {
  Beginner:     allExercises.filter(e => e.difficulty === "Beginner"),
  Intermediate: allExercises.filter(e => e.difficulty === "Intermediate"),
  Advanced:     allExercises.filter(e => e.difficulty === "Advanced"),
};
